export const getTeam = () => {
  return [
    {
      image: require('./img/uri.jpg'),
      name: 'Uriel Kugelmass',
      title: 'Frontend Developer',
      description: 'Uriel is currently a Computer Science Senior at UT from Montevideo, Uruguay. Outside of school, you can find him playing soccer or reading books, but never taking long walks on the beach.',
      issue_id: '2825936',
      commit_ids: ['Uriel Kugelmass'],
      tests_id: '@Uriel@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,
    },
    {
      image: require('./img/evan.jpg'),
      name: 'Evan Weiss',
      title: 'Full-Stack Developer',
      description: 'Evan is a Junior at UT studying Computer Science and was born in Dallas, TX. A fun fact about him is that he has been skydiving. He does not enjoy long walks on the beach because he gets bored easily.',
      issue_id: '2773618',
      commit_ids: ['Evan Weiss', 'eweiss97'],
      tests_id: '@Evan@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,
    },
    {
      image: require('./img/yoav.jpg'),
      name: 'Yoav Ilan',
      title: 'Frontend Developer',
      description: 'Yoav is a Junior Computer Science student from Dallas, TX, and Israel prior to that. He only enjoys medium walks on the beach that are between 10 to 15 minutes inclusive.',
      issue_id: '2788669',
      commit_ids: ['Yoav Ilan'],
      tests_id: '@Yoav@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,
    },
    {
      image: require('./img/albert.jpg'),
      name: 'Albert Luu',
      title: 'Frontend Developer',
      description: 'Albert is a Junior Computer Science student from Arlington, Texas. Outside of school, he enjoys biking, gaming, and playing piano. Unfortunately, long walks on the beach are very tiring to him.',
      issue_id: '2803538',
      commit_ids: ['Albert Luu'],
      tests_id: '@Albert@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,
    },
    {
      image: require('./img/colin.jpg'),
      name: 'Colin Frick',
      title: 'Full-Stack Developer',
      description: 'Colin is a Junior Computer Science student at UT from Houston, Texas. He is interested in studying artificial intelligence and web development. He does not enjoy walking of any form.',
      issue_id: '2776165',
      commit_ids: ['cfrick16'],
      tests_id: '@Colin@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,
    },
    {
      image: require('./img/daniel.jpg'),
      name: 'Daniel Chruscielski',
      title: 'Full-Stack Developer',
      description: 'Daniel is a third year Computer Science student at UT. He enjoys making long walks on the beach shorter by finding the shortest possible path. In his spare time, he plays the drums, listens to jazz, and generally does what you would expect from someone who lives in Austin.',
      issue_id: '2773160',
      commit_ids: ['Daniel Chruscielski'],
      tests_id: '@Daniel@',
      commits: 0,
      issues: 0,
      tests: 0,
      acceptance_tests: 0,   
    },
  ];
}
